name=VirtualMemoryEngine
version=1.0.0
author=Zoran Stepanoski
maintainer=Zoran Stepanoski
sentence=S-OS High-Performance Virtual Memory Engine for ESP32.
paragraph=Enables dynamic compressed RAM-to-Flash paging using RangeCoder and LZ77.
category=Data Processing
url=https://zoranstepanoski-prof-website.fly.dev/
architectures=esp32
includes=VirtualMemoryEngine.h
precompiled=true
ldflags=-lVirtualMemoryEngine